#!/bin/bash
# vignette config file

## --------------------------- Root Directories -----
 
export SCRIPT_ROOT=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA
export WKD_ROOT=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/Whole_Transcriptome/1_sample_multiple_flowcell/output
export META_ROOT=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/Whole_Transcriptome/1_sample_multiple_flowcell/input/metadata
export LOGEN_ROOT=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LOGen

## --------------------------- Input -----

export NAME=mousePilot
export SAMPLESHEET=${META_ROOT}/vignette_samplesheet.csv
export numBatches=2
export numSamples=2

## --------------------------- Multiplexing -----

export MULTIPLEXING=FALSE
export RAW_ROOT_DIR=(
/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/Whole_Transcriptome/1_sample_multiple_flowcell/input/data/mouse_pilot/fastq_pass 
/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/Whole_Transcriptome/1_sample_multiple_flowcell/input/data/mouse_pilot2/fastq_pass
) 
export SEQUENCING=whole
export MERGE_FASTQ=TRUE

## --------------------------- References -----

export GENOME_FASTA=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/References/Genome/mouse/mm10.fa
export GENOME_GTF=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/References/Genome/mouse/gencode.vM22.annotation.gtf

## --------------------------- Software	 -----

export SQANTI3_DIR=/lustre/projects/Research_Project-MRC148213/lsl693/software/SQANTI3
export TRANSCRIPTCLEAN_DIR=/lustre/projects/Research_Project-MRC148213/lsl693/software/TranscriptClean

## --------------------------- Additional parameters -----

# ONT kit (PCS109,PCS110,PCS111,PCS114,LSK114,PCB111,PCB114)
ONTKit=LSK114

# isoseq collapse threshold
minalnidentity=0.95
minalncoverage=0.85
maxfuzzyjunction=0 
max5pdiff=100
max3pdiff=200

# filtering expression
export nreads=3
export nsamples=3

# monoexonic filtering
monoexonic=1

# target genes for additional filtering
tgenesFile=NA

## --------------------------- CPAT -----

export HEXAMER=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/References/CPAT/Mouse_Hexamer.tsv
export LOGITMODEL=/lustre/projects/Research_Project-MRC148213/lsl693/scripts/LRPipeline/ont_cDNA/vignette/References/CPAT/Mouse_logitModel.RData